const scratchCycleData = [
    {
        id: 1,
        title: "Trigger",
        desc: "Allergen, dry air, or heat activates keratinocytes to release TSLP and IL-33",
    },
    {
        id: 2,
        title: "Itch Signal",
        desc: "C-fibre pruriceptors fire. IL-31 binds directly to nerve endings, the cytokine itch",
    },
    {
        id: 3,
        title: "Scratch",
        desc: "Physical trauma damages keratinocytes and causes further barrier disruption",
    },
    {
        id: 4,
        title: "Amplification",
        desc: "More TSLP released. Last cellsdegranulate. The next itch is stronger than the last",
    },
]

const ScratchCycle = () => {
    return (
        <>
            <section className="
                px-[1rem] sm:px-[5%] lg:px-[7%]
                py-[2rem] sm:py-[1.5rem] lg:py-[1.3rem] xl:py-[1.7rem] 2xl:py-[2rem]
            ">
                <span className="
                    text-[1.1rem] sm:text-[1.2rem] lg:text-[0.95rem] xl:text-[1.1rem] 2xl:text-[1.2rem]
                    text-[#363636]
                " data-aos="fade" data-aos-once="true">
                   — THE ITCH-SCRATCH CYCLE
                </span>
                <h5 className="
                    text-[1.8rem] sm:text-[1rem] lg:text-[3.2rem] xl:text-[3.6rem] 2xl:text-[4rem] leading-[1]
                    mt-[0.5rem] sm:mt-[0.5rem] lg:mt-[0.8rem] xl:mt-[0.9rem] 2xl:mt-[1rem]
                " data-aos="fade-up">
                    Why Scratching <br /> Makes Eczema Worse
                </h5>
                <p className="
                    text-[1.1rem] sm:text-[1.2rem] lg:text-[0.95rem] xl:text-[1.1rem] 2xl:text-[1.2rem]
                    mt-[0.5rem] sm:mt-[0.5rem] lg:mt-[0.8rem] xl:mt-[0.9rem] 2xl:mt-[1rem]
                    text-[#363636]
                " data-aos="fade" data-aos-once="true"> 
                    The itch in eczema is not simple. It is driven by a neural-immune loop, a cycle in which each scratch literally amplifies the next itch signal. Understanding this mechanism is key to understanding why eczema is so difficult to control through willpower alone.
                </p>

                {/* Row */}
                <div className="
                    mt-[3rem] sm:mt-[2.5rem] lg:mt-[2.6rem] xl:mt-[2.8rem] 2xl:mt-[3rem]
                    flex justify-between flex-wrap
                ">
                    {scratchCycleData.map((item) => {
                        return (
                            <div key={item.id} className="
                                w-[23%] bg-[#fbf4ea] overflow-hidden
                                p-[1.3rem] sm:p-[1.2rem] lg:p-[1.1rem] xl:p-[1.2rem] 2xl:p-[1.3rem]
                                rounded-2xl shadow-md hover:shadow-lg
                                hover:scale-[1.02] transition duration-300
                            ">
                                <span className="
                                    block text-[1.8rem] sm:text-[1.5rem] lg:text-[1.6rem] xl:text-[1.7rem] 2xl:text-[1.8rem]
                                " data-aos="zoom-out" data-aos-once="true">
                                    0{item.id}
                                </span>
                                <span className="
                                    block text-[1.6rem] sm:text-[1.2rem] lg:text-[1.4rem] xl:text-[1.5rem] 2xl:text-[1.6rem]
                                    mt-[0.1rem]
                                " style={{ fontFamily: `"OrdinaryBoys", sans-serif` }} data-aos="fade-right" data-aos-once="true">
                                    {item.title}
                                </span>
                                <p className="
                                    text-[1.1rem] sm:text-[1.1rem] lg:text-[0.9rem] xl:text-[1rem] 2xl:text-[1.1rem]
                                    mt-[0.5rem] sm:mt-[0.5rem] lg:mt-[0.8rem] xl:mt-[0.9rem] 2xl:mt-[1rem]
                                    text-[#363636]
                                " data-aos="fade" data-aos-once="true">
                                    {item.desc}
                                </p>
                            </div>
                        )
                    })}
                </div>

                <p className="
                    text-[1.1rem] sm:text-[1.1rem] lg:text-[0.9rem] xl:text-[1rem] 2xl:text-[1.1rem]
                    mt-[2rem] sm:mt-[2rem] lg:mt-[2.8rem] xl:mt-[2.9rem] 2xl:mt-[3rem]
                    text-[#363636]
                " data-aos="fade" data-aos-once="true">
                    At the neurological level, chronic itch rewires the dorsal root ganglia, the brain starts to interpret even normal touch as itch. This is called peripheral sensitisation, and it explains why eczema patients often experience itch without any visible trigger in chronic stages. The sensation is real, and it is generated by the nervous system itself.
                </p>
            </section>
        </>
    )
}

export default ScratchCycle
